config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/courses', to:'static_pages#courses', via:'get'
  match '/community', to:'static_pages#community', via:'get'
  match '/about', to:'static_pages#about', via:'get'
  match '/terms', to:'static_pages#terms', via:'get'
  match '/privacy', to:'static_pages#privacy', via:'get'
  match '/contact', to:'static_pages#contact', via:'get'
  match '/signup', to:'users#new', via: 'get'
  match '/signin', to:'sessions#new', via: 'get'
  match '/signout', to:'sessions#destroy', via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email=email.downcase}
	before_create :create_remember_token
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX},
				uniqueness: {case_sensitive: false}
	has_secure_password
	validates :password, length: {minimum: 6}

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			# Sign the user in and redirect to the user's show page
			sign_in user
			redirect_back_or user
		else
			flash.now[:error] ='Invalid email/password combination'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def courses
  end

  def community
  end

  def about
  end

  def terms
  end

  def privacy
  end

  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)  # Not the final implementation
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to TrueSchool"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def edit
  end

  

  def update
    if @user.update_attributes(user_params)
      # Handle a successful update
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
      User.find(params[:id]).destroy
      flash[:success] = "User deleted"
      redirect_to users_url
    end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	  end  

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end 	

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end	

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end

	def sign_out
		current_user.update_attribute(:remember_token, 
						User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#Returns the Gravatar (http://gravatar.com/) for the given user
	def gravatar_for(user, options = {size: 50})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class:"gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <nav>
    <ul>
      <li><%= link_to "Terms & Conditions",   terms_path %></li>
      <li><%= link_to "Privacy Policy",   privacy_path %></li>
      <li><%= link_to "Contact Us", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "TrueSchool", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Courses",    courses_path%></li>
          <li><%= link_to "Community",    community_path %></li>
          <li><%= link_to "About Us",    about_path %></li>

          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
            <% else %>
               <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Ts2</title>
  		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  		<%= csrf_meta_tags %>
  		<%= render 'layouts/shim' %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key%>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@user.errors.count, "error") %>
		</div>
		<ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li>*<%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %> 

app/views/static_pages/about.html.erb
<h1>About Us</h1>
<p>
	We are a team brought together by a shared vision of making learning a seamless and fulfilling experience. We are trying to personalize the learning experience by leveraging technology thus enabling learners to identify their weaknesses and harness their strengths. We also understand that each learner requires a tailor-made learning experience to suit their pace.
</p>
<p>
	Pooling in our varied experiences, we aspire to create a platform enabling students to connect with similar minded peers for sharing knowledge which essentially gets lost in the current system of isolated learning. Keeping ourselves updated to the current research in the field of education technology, our philosophy is to make learning as interesting, engaging and interactive as possible.
</p>
<p>
	We encourage learners to think and explore, and in the process inculcate a self-driven enthusiasm to learn more and make the process satisfying and sustainable.
</p>
<p>
	We aspire to create life-long learners because when you think, you learn and then you grow.
</p>
<p>
	This is a beta site for testing. Complete site will be launched soon. We request the learners to provide their valuable feedback in order to make their experience better. Thanks.
</p>

app/views/static_pages/community.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TrueSchool | Community</title>
	</head>

	<body>
		<h1>Community</h1>

		<p>
			Welcome to the TrueSchool Community.
		</p>
	</body>
</html>

app/views/static_pages/courses.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>TrueSchool | Courses</title>
	</head>

	<body>
		<h1>Courses</h1>

		<p>
			Prepare for JEE online
		</p>
	</body>
</html>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Welcome to TrueSchool</h1>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/static_pages/privacy.html.erb
<h1>Privacy Policy</h1>
<p>
	This Privacy Policy governs the manner in which TrueSchool collects, uses, maintains and discloses information collected from users (each, a “User”) of the <a href="http://trueschool.co.in">http://trueschool.co.in</a> website (“Site”). This privacy policy applies to the Site and all products and services offered by TrueSchool.
</p>

<h3>Personal identification information</h3>
<p>
	We may collect personal identification information from Users in a variety of ways, including, but not limited to, when Users visit our site, register on the site, fill out a form, and in connection with other activities, services, features or resources we make available on our Site. Users may be asked for, as appropriate, name, email address, phone number. Users may, however, visit our Site anonymously. We will collect personal identification information from Users only if they voluntarily submit such information to us. Users can always refuse to supply personally identification information, except that it may prevent them from engaging in certain Site related activities.
</p>

<h3>Non-personal identification information</h3>
<p>
	We may collect non-personal identification information about Users whenever they interact with our Site. Non-personal identification information may include the browser name, the type of computer and technical information about Users means of connection to our Site, such as the operating system and the Internet service providers utilized and other similar information.
</p>

<h3>Web browser cookies</h3>
<p>
	Our Site may use “cookies” to enhance User experience. User’s web browser places cookies on their hard drive for record-keeping purposes and sometimes to track information about them. User may choose to set their web browser to refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of the Site may not function properly.
</p>

<h3>How we use collected information</h3>
<p>
	TrueSchool may collect and use Users personal information for the following purposes:
</p>
<dl>
	<dt>To improve customer service</dt>
	<dd>Information you provide helps us respond to your customer service requests and support needs more efficiently.</dd>

	<dt>To personalize user experience</dt>
	<dd>We may use information in the aggregate to understand how our Users as a group use the services and resources provided on our Site.</dd>

	<dt>To improve our Site</dt>
	<dd>We may use feedback you provide to improve our products and services.</dd>

	<dt>To process payments</dt>
	<dd>We may use the information Users provide about themselves when placing an order only to provide service to that order. We do not share this information with outside parties except to the extent necessary to provide the service.</dd>

	<dt>To run a promotion, contest, survey or other Site feature</dt>
	<dd>To send Users information they agreed to receive about topics we think will be of interest to them.</dd>

	<dt>To send periodic emails</dt>
	<dd>We may use the email address to send User information and updates pertaining to their order. It may also be used to respond to their inquiries, questions, and/or other requests. If User decides to opt-in to our mailing list, they will receive emails that may include company news, updates, related product or service information, etc. If at any time the User would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email or User may contact us via our Site.</dd>
</dl>

<h3>How we protect your information</h3>
<p>
	We adopt appropriate data collection, storage and processing practices and security measures to protect against unauthorized access, alteration, disclosure or destruction of your personal information, username, password, transaction information and data stored on our Site.
</p>

<p>
	Sensitive and private data exchange between the Site and its Users happens over a SSL secured communication channel and is encrypted and protected with digital signatures.
</p>

<h3>Sharing your personal information</h3>
<p>
	We do not sell, trade, or rent Users personal identification information to others. We may share generic aggregated demographic information not linked to any personal identification information regarding visitors and users with our business partners, trusted affiliates and advertisers for the purposes outlined above.We may use third party service providers to help us operate our business and the Site or administer activities on our behalf, such as sending out newsletters or surveys. We may share your information with these third parties for those limited purposes provided that you have given us your permission.
</p>

<h3>Third party websites</h3>
<p>
	Users may find advertising or other content on our Site that link to the sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third parties. We do not control the content or links that appear on these sites and are not responsible for the practices employed by websites linked to or from our Site. In addition, these sites or services, including their content and links, may be constantly changing. These sites and services may have their own privacy policies and customer service policies. Browsing and interaction on any other website, including websites which have a link to our Site, is subject to that website’s own terms and policies.
</p>

<h3>Advertising</h3>
<p>
	Ads appearing on our site may be delivered to Users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile non personal identification information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy does not cover the use of cookies by any advertisers.
</p>

<h3>Changes to this privacy policy</h3>
<p>
	TrueSchool has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.
</p>

<h3>Your acceptance of these terms</h3>
<p>
	By using this Site, you signify your acceptance of this policy and <a hreff="trueschool.co.in/terms">terms of service</a>. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.
</p>

<h3>Contacting us</h3>
<p>
	If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at: webmaster@trueschool.co.in
</p>

app/views/static_pages/terms.html.erb
<h1>Terms & Conditions</h1>
<h2>Terms and Conditions of Use of TrueSchool</h2>
<ol>
	<li><h3>Acceptance The Use Of TrueSchool Terms and Conditions</h3></li>
		<p>
			Your access to and use of TrueSchool is subject exclusively to these Terms and Conditions. You will not use the Website for any purpose that is unlawful or prohibited by these Terms and Conditions. By using the Website you are fully accepting the terms, conditions and disclaimers contained in this notice. If you do not accept these Terms and Conditions you must immediately stop using the Website.
		</p>

	<li><h3>Credit card details</h3></li>
		<p>
			TrueSchool will never ask for Credit Card details and request that you do not enter it on any of the forms on TrueSchool.
		</p>

	<li><h3>Advice</h3></li>
		<p>
			The contents of TrueSchool website do not constitute advice and should not be relied upon in making or refraining from making, any decision.
		</p>

	<li><h3>Change of Use</h3>
		<p>
			TrueSchool reserves the right to:
		</p>
		<ol>
			<li>
				change or remove (temporarily or permanently) the Website or any part of it without notice and you confirm that TrueSchool shall not be liable to you for any such change or removal and.
			</li>
			<li>
				change these Terms and Conditions at any time, and your continued use of the Website following any changes shall be deemed to be your acceptance of such change.
			</li>
		</ol>
	</li>

	<li><h3>Links to Third Party Websites</h3></li>
		<p>
			TrueSchool Website may include links to third party websites that are controlled and maintained by others. Any link to other websites is not an endorsement of such websites and you acknowledge and agree that we are not responsible for the content or availability of any such sites.
		</p>

	<li><h3>Copyright</h3></li>
	<ol>
			<li>
				All copyright, trade marks and all other intellectual property rights in the Website and its content (including without limitation the Website design, text, graphics and all software and source codes connected with the Website) are owned by or licensed to TrueSchool or otherwise used by TrueSchool as permitted by law.
			</li>
			<li>
				In accessing the Website you agree that you will access the content solely for your personal, non-commercial use. None of the content may be downloaded, copied, reproduced, transmitted, stored, sold or distributed without the prior written consent of the copyright holder. This excludes the downloading, copying and/or printing of pages of the Website for personal, non-commercial home use only.
			</li>
		</ol>

	<li><h3>Disclaimers and Limitation of Liability</h3></li>
	<ol>
			<li>
				The Website is provided on an AS IS and AS AVAILABLE basis without any representation or endorsement made and without warranty of any kind whether express or implied, including but not limited to the implied warranties of satisfactory quality, fitness for a particular purpose, non-infringement, compatibility, security and accuracy.
			</li>
			<li>
				To the extent permitted by law, TrueSchool will not be liable for any indirect or consequential loss or damage whatever (including without limitation loss of business, opportunity, data, profits) arising out of or in connection with the use of the Website.
			</li>
			<li>
				TrueSchool makes no warranty that the functionality of the Website will be uninterrupted or error free, that defects will be corrected or that the Website or the server that makes it available are free of viruses or anything else which may be harmful or destructive.
			</li>
			<li>
				Nothing in these Terms and Conditions shall be construed so as to exclude or limit the liability of TrueSchool for death or personal injury as a result of the negligence of TrueSchool or that of its employees or agents.
			</li>
		</ol>

	<li><h3>Indemnity</h3></li>
		<p>
			You agree to indemnify and hold TrueSchool and its employees and agents harmless from and against all liabilities, legal fees, damages, losses, costs and other expenses in relation to any claims or actions brought against TrueSchool arising out of any breach by you of these Terms and Conditions or other liabilities arising out of your use of this Website.
		</p>

	<li><h3>Severance</h3></li>
		<p>
			If any of these Terms and Conditions should be determined to be invalid, illegal or unenforceable for any reason by any court of competent jurisdiction then such Term or Condition shall be severed and the remaining Terms and Conditions shall survive and remain in full force and effect and continue to be binding and enforceable.
		</p>

	<li><h3>Governing Law</h3></li>
		<p>
			These Terms and Conditions shall be governed by and construed in accordance with the law of India and you hereby submit to the exclusive jurisdiction of the Indian courts.
		</p>
</ol>

	<p>
		For any further information please email-webmaster@trueschool.co.in
	</p>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
  	| <%= link_to "delete", user, method: :delete,
  			data: {confirm: "Are you sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirm Password" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

		<% end %>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
		<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
		<% end %>

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>